import type { ComplianceRecord } from './types'

export const mockComplianceData: ComplianceRecord[] = [
  // FIPS 140-3 Examples
  {
    id: 'fips-1',
    source: 'NIST',
    date: '2024-11-15',
    link: 'https://csrc.nist.gov/projects/cryptographic-module-validation-program/validated-modules/search',
    type: 'FIPS 140-3',
    status: 'Active',
    pqcCoverage: 'ML-KEM (Planned)',
    productName: 'QuantumSafe HSM v2',
    productCategory: 'Hardware Security Module',
    vendor: 'SecureCorp Inc.',
  },
  {
    id: 'fips-2',
    source: 'NIST',
    date: '2024-10-02',
    link: 'https://csrc.nist.gov/projects/cryptographic-module-validation-program/validated-modules/search',
    type: 'FIPS 140-3',
    status: 'In Process',
    pqcCoverage: false,
    productName: 'Enterprise Encryptor X1',
    productCategory: 'Network Appliance',
    vendor: 'NetShield Dynamics',
  },
  {
    id: 'fips-3',
    source: 'NIST',
    date: '2025-01-10',
    link: 'https://csrc.nist.gov/projects/cryptographic-module-validation-program/validated-modules/search',
    type: 'FIPS 140-3',
    status: 'Active',
    pqcCoverage: 'Dilithium (Sig)',
    productName: 'TrustGuard Key Manager',
    productCategory: 'Key Management',
    vendor: 'TrustWorks Global',
  },

  // ACVP Examples
  {
    id: 'acvp-1',
    source: 'NIST',
    date: '2024-12-01',
    link: 'https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/validation-search',
    type: 'ACVP',
    status: 'Active',
    pqcCoverage: 'SHA-3',
    productName: 'CryptoLib Core v3.0',
    productCategory: 'Software Library',
    vendor: 'OpenForge Systems',
  },
  {
    id: 'acvp-2',
    source: 'NIST',
    date: '2024-09-20',
    link: 'https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/validation-search',
    type: 'ACVP',
    status: 'Historical',
    pqcCoverage: false,
    productName: 'LegacyCrypto Mod',
    productCategory: 'Firmware',
    vendor: 'OldTech Solutions',
  },

  // Common Criteria Examples
  {
    id: 'cc-1',
    source: 'Common Criteria',
    date: '2024-08-15',
    link: 'https://www.commoncriteriaportal.org/products/',
    type: 'Common Criteria',
    status: 'Active',
    pqcCoverage: false,
    productName: 'SecureOS v5.2',
    productCategory: 'Operating System',
    vendor: 'Global OS Ltd.',
  },
  {
    id: 'cc-2',
    source: 'Common Criteria',
    date: '2025-02-01',
    link: 'https://www.commoncriteriaportal.org/products/',
    type: 'Common Criteria',
    status: 'Pending',
    pqcCoverage: 'Hybrid (Classic/PQC)',
    productName: 'NextGen Firewall Z',
    productCategory: 'Network Security',
    vendor: 'CyberWall',
  },
]
