// SPDX-License-Identifier: GPL-3.0-only
/**
 * Sync script: read pqctoday-sandbox scenarios.ts → project to a trimmed
 * manifest for the PQC Timeline App Playground (src/data/sandboxScenarios.ts).
 *
 * Run: npm run sync:sandbox
 * Override source repo path:  SANDBOX_REPO_PATH=/abs/path npm run sync:sandbox
 *
 * The generated file is committed so the main build does not depend on the
 * private sandbox repo being present on disk.
 */
import { existsSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, '..')
const sandboxRoot = process.env.SANDBOX_REPO_PATH ?? resolve(repoRoot, '..', 'pqctoday-sandbox')
const scenariosPath = resolve(sandboxRoot, 'ui/src/data/scenarios.ts')
const outPath = resolve(repoRoot, 'src/data/sandboxScenarios.ts')

if (!existsSync(scenariosPath)) {
  console.warn(
    `[sync-sandbox-scenarios] source missing: ${scenariosPath}\n` +
      `Set SANDBOX_REPO_PATH or clone pqctoday-sandbox next to this repo. ` +
      `Leaving existing ${outPath} untouched.`
  )
  process.exit(0)
}

type SourceBadge = { label: string; variant: string }
type SourceScenario = {
  id: string
  title: string
  icon: string
  badges: SourceBadge[]
  useCase: string
  tool: { name: string; url: string }
  difficulty?: 'beginner' | 'intermediate' | 'advanced'
}
type SourceTrack = {
  id: string
  label: string
  subtitle: string
  difficulty: string
  scenarioIds: string[]
}

const mod = (await import(scenariosPath)) as {
  SCENARIOS: SourceScenario[]
  LEARNING_TRACKS: SourceTrack[]
}

const trackByScenarioId = new Map<string, string>()
for (const t of mod.LEARNING_TRACKS) {
  for (const id of t.scenarioIds) trackByScenarioId.set(id, t.id)
}

type TrackId = 'infrastructure' | 'web' | 'applications' | 'quantum'
const KNOWN_TRACK_IDS: readonly TrackId[] = ['infrastructure', 'web', 'applications', 'quantum']
const isKnownTrack = (s: string): s is TrackId => (KNOWN_TRACK_IDS as readonly string[]).includes(s)

const inferTrack = (id: string): TrackId => {
  const assigned = trackByScenarioId.get(id)
  if (assigned && isKnownTrack(assigned)) return assigned
  if (id.includes('qkd') || id.includes('sequence') || id.includes('discovery')) return 'quantum'
  if (
    id.includes('tls') ||
    id.includes('ssh') ||
    id.includes('dns') ||
    id.includes('chronyd') ||
    id.includes('haproxy') ||
    id.includes('pqcflow') ||
    id.includes('migration')
  )
    return 'web'
  if (
    id.includes('web3') ||
    id.includes('algorand') ||
    id.includes('besu') ||
    id.includes('mqtt') ||
    id.includes('jwt') ||
    id.includes('sigstore') ||
    id.includes('supply') ||
    id.includes('sops') ||
    id.includes('sequoia') ||
    id.includes('osslsigncode') ||
    id.includes('firmware') ||
    id.includes('stepca') ||
    id.includes('database') ||
    id.includes('confidential')
  )
    return 'applications'
  return 'infrastructure'
}

const projected = mod.SCENARIOS.map((s) => ({
  id: s.id,
  title: s.title,
  emoji: s.icon,
  useCase: s.useCase,
  algorithms: Array.from(
    new Set(
      s.badges
        .filter((b) => b.variant === 'primary' || b.variant === 'secondary')
        .map((b) => b.label)
    )
  ),
  difficulty: s.difficulty ?? 'intermediate',
  trackId: inferTrack(s.id),
  tool: { name: s.tool.name, url: s.tool.url },
}))

const tracks = mod.LEARNING_TRACKS.map((t) => ({
  id: t.id,
  label: t.label,
  subtitle: t.subtitle,
  difficulty: t.difficulty,
}))

const header = `// SPDX-License-Identifier: GPL-3.0-only
// Generated by scripts/sync-sandbox-scenarios.ts — do not edit by hand.
// Source: pqctoday-sandbox/ui/src/data/scenarios.ts
// Regenerate with: npm run sync:sandbox
`

const fileBody = `${header}
export type SandboxTrackId = 'infrastructure' | 'web' | 'applications' | 'quantum'
export type SandboxDifficulty = 'beginner' | 'intermediate' | 'advanced'

export interface SandboxScenario {
  id: string
  title: string
  emoji: string
  useCase: string
  algorithms: string[]
  difficulty: SandboxDifficulty
  trackId: SandboxTrackId
  tool: { name: string; url: string }
}

export interface SandboxTrack {
  id: string
  label: string
  subtitle: string
  difficulty: string
}

export const SANDBOX_SCENARIOS: SandboxScenario[] = ${JSON.stringify(projected, null, 2)}

export const SANDBOX_TRACKS: SandboxTrack[] = ${JSON.stringify(tracks, null, 2)}
`

writeFileSync(outPath, fileBody, 'utf8')
console.log(
  `[sync-sandbox-scenarios] wrote ${projected.length} scenarios + ${tracks.length} tracks → ${outPath}`
)
